name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Spustí se každý den v půlnoci
  workflow_dispatch:     # Možnost ručního spuštění

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: MarekVoe
          outputs: |
            ./dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
